config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'courses#index'
  get 'courses', to: 'courses#index', as: 'courses'
  get 'courses/new', to: 'courses#new'
  get 'about', to: 'pages#about'

  resources :students, except: :destroy

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'course_enroll', to: 'student_courses#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :name, presence: true, length: { minimum: 5, maximum: 50 }
  validates :short_name, presence: true, length: { minimum: 3, maximum: 15 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }

  has_many :student_courses
  has_many :students, through: :student_courses
end

app/models/student.rb
class Student < ApplicationRecord
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { minimum: 5, maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 105 },
                    uniqueness: { case_sensitive: false },
                    format: { with: VALID_EMAIL_REGEX }

  has_secure_password

  has_many :student_courses
  has_many :courses, through: :student_courses
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  before_action :require_user

  def current_user
    @current_user ||= Student.find(session[:student_id]) if logged_in?
  end

  def logged_in?
    session[:student_id].present?
  end

  def require_user
    unless logged_in?
      flash[:notice] = 'You must be logged in to perform this action!'
      redirect_to login_path
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :require_user

  def index
    @courses = Course.all
  end

  def new

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :require_user

  def about

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_user, only: [:new, :create]

  def create
    student = Student.find_by(email: params[:session][:email].downcase)
    if student&.authenticate(params[:session][:password])
      session[:student_id] = student.id
      flash[:notice] = 'Logged in!'
      redirect_to root_path
    else
      flash.now[:alert] = 'Invalid credentials!..'
      render :new
    end
  end

  def destroy
    flash[:notice] = 'Successfully logged out!'
    session[:student_id] = nil

    redirect_to root_path
  end
end

app/controllers/student_courses_controller.rb
class StudentCoursesController < ApplicationController
  before_action :set_course, only: :create

  def create
    if current_user.courses.include? @course_to_add
      flash[:notice] = 'Something went wrong with your enrollment'
      redirect_to root_path
    else
      StudentCourse.create(course: @course_to_add, student: current_user)
      flash[:notice] = "Congrats, you enrolled in #{@course_to_add.name}!"
      redirect_to current_user
    end
  end

  def set_course
    @course_to_add = Course.find(params[:course_id])
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[show edit update]
  skip_before_action :require_user, only: %i[new create]
  before_action :require_same_student, only: %i[edit update]

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      flash[:notice] = 'You have been successfully signed up!'
      redirect_to @student
    else
      render :new
    end
  end

  def update
    if @student.update(student_params)
      flash[:notice] = 'Student information has been successfully updated!'
      redirect_to students_path
    else
      render :edit
    end
  end

  private

  def student_params
    params.require(:student).permit(:name, :email, :password, :password_confirmation)
  end

  def set_student
    @student = Student.find(params[:id])
  end

  def require_same_student
    unless @student == current_user
      flash[:notice] = 'Invalid request!'
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def session_link
    return link_to 'Log out', logout_path, method: :delete if logged_in?

    link_to 'Log in', login_path
  end
end

app/views/courses/index.html.erb
<div class="row">
  <div class="col s12 center-align">
    <h1>Course Listing</h1>
  </div>
</div>

<div class="row">
  <% @courses.each do |course| %>
    <div class="col s12 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= course.short_name %>: <%= course.name %></span>
          <p><%= course.description %></p>
        </div>
        <div class="card-action">
          <% if logged_in? && !current_user.courses.include?(course) %>
            <%= link_to 'Enroll', course_enroll_path(course_id: course.id), method: :post %>
          <% end %>
          <a href="#">Info</a>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/courses/new.html.erb
<h1>hi from app/views/courses/new.html.erb!</h1>

app/views/layouts/_flash.html.erb
<% flash.each do |_k, message| %>
  <div class="container">
    <div class="row sign-up-form">
      <div class="col s12 l12 m12">
        <div class="card-panel red lighten-2" id="fade-out-target">
          <span class="white-text">
            <%= message %>
          </span>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="row">
    <div class="col l6 s12">
      <h5 class="white-text">Tech University</h5>
      <p class="grey-text text-lighten-4">The future of development training.</p>
    </div>
    <div class="col l4 offset-l2 s12">
      <h5 class="white-text">Information</h5>
      <ul>
        <li><a class="grey-text text-lighten-3" href="#!">Help</a></li>
        <li><a class="grey-text text-lighten-3" href="#!">About</a></li>
        <li><a class="grey-text text-lighten-3" href="#!">Contact us</a></li>
      </ul>
    </div>
  </div>
</div>
<div class="footer-copyright">
  <div class="container">
    © 2020 Tech University
    <a class="grey-text text-lighten-4 right" href="#!">About</a>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<ul id="dropdown1" class="dropdown-content">
  <li><%= session_link %></li>
  <% if logged_in? %>
    <li><%= link_to 'View your profile', student_path(current_user) %></li>
  <% end %>
</ul>
<ul id="dropdown2" class="dropdown-content">
  <li><%= session_link %></li>
  <% if logged_in? %>
    <li><%= link_to 'View your profile', student_path(current_user) %> </li>
  <% end %>
</ul>
<nav>
  <div class="container">
    <div class="nav-wrapper">
      <%= link_to 'Tech University', root_path, class: 'brand-logo right' %>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul id="nav-mobile" class="left hide-on-med-and-down">
        <li><%= link_to 'Courses', courses_path %></li>
        <% if logged_in? %>
          <li><%= link_to 'Students', students_path %></li>
        <% end %>
        <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Account<i class="material-icons right">arrow_drop_down</i></a></li>
      </ul>
    </div>
  </div>
</nav>

<ul class="sidenav" id="mobile-demo">
  <li><%= link_to 'Courses', courses_path %></li>
  <% if logged_in? %>
    <li><%= link_to 'Students', students_path %></li>
  <% end %>
  <li><a class="dropdown-trigger" href="#!" data-target="dropdown2">Account<i class="material-icons right">arrow_drop_down</i></a></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tech University</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
      <%= render 'layouts/flash' %>
    </header>
    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>
    <footer class="page-footer">
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>

app/views/pages/about.html.erb
<h1>hi from app/views/pages/about.html.erb!</h1>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="container">
    <div class="row sign-up-form">
      <div class="col s12 l12 m12">
        <div class="card-panel red lighten-2">
          <span class="white-text">
            <strong>
              <%= pluralize(obj.errors.count, "error") %> prohibited your
              profile from being created!
            </strong>
            <ul>
              <% obj.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </span>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/students/_errors.html.erb
<% if @student.errors.any? %>
  <div class="container">
    <div class="row sign-up-form">
      <div class="col s12 l12 m12">
        <div class="card-panel red lighten-2">
          <span class="white-text">
            <strong>
              <%= pluralize(@student.errors.count, "error") %> prohibited your
              profile for being created!
            </strong>
            <ul>
              <% @student.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </span>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/students/_form.html.erb
<%= render 'shared/errors', obj: @student %>

<div class="container">
  <div class="row sign-up-form center-align">
    <div class="col s12 l12 m12">
      <div class="card-panel">
        <h3 class="header">
          <%= @student.new_record? ? 'Sign up' : 'Edit your profile' %>
        </h3>
        <div class="row">
          <%= form_with(model: @student, local: true, html: { class: 'col s12' }) do |f| %>
            <div class="row">
              <div class="input-field col s6">
                <i class="material-icons prefix">account_circle</i>
                <%= f.text_field :name, autofocus: true %>
                <%= f.label 'Name' %>
              </div>
              <div class="input-field col s6">
                <i class="material-icons prefix">email</i>
                <%= f.email_field :email %>
                <%= f.label :email %>
              </div>
              <div class="input-field col s6">
                <i class="material-icons prefix">password</i>
                <%= f.password_field :password %>
                <%= f.label :password %>
              </div>
              <div class="input-field col s6">
                <i class="material-icons prefix">password</i>
                <%= f.password_field :password_confirmation %>
                <%= f.label :password_confirmation %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.button @student.new_record? ? 'Sign up' : 'Edit student information',
                             class: 'btn waves-effect waves-light right' %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/edit.html.erb
<%= render 'form' %>

app/views/students/index.html.erb
<div class="row">
  <div class="col s12 center-align">
    <h1>Students Directory</h1>
  </div>
</div>

<div class="row">
  <% @students.each do |student| %>
    <div class="col s12 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Name:<%= student.name %></span>
          <p>Email:<%= student.email %></p>
          <p>Course enrollments</p>
        </div>
        <div class="card-action">
          <%= link_to 'View profile', student_path(student) %>
        </div>
      </div>
    </div>
  <% end %>

  <%= link_to new_student_path, class: 'btn waves-effect waves-light' do %>
    Add new student <i class="material-icons right">send</i>
  <% end %>
</div>

app/views/students/new.html.erb
<%= render 'form' %>

app/views/students/show.html.erb
<div class="row">
  <div class="col s12 center-align">
    <h1><%= @student.name %>'s profile</h1>
  </div>
</div>

<div class="row">
  <div class="col s12 m12">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title">Name:<%= @student.name %></span>
        <p>Email:<%= @student.email %></p>
        <% if @student.courses.present? %>
          <p>Course enrollments</p>
          <ul>
            <% @student.courses.each do |course| %>
              <li><%= course.name %></li>
            <% end %>
          </ul>
        <% else %>
          None
        <% end %>
      </div>
      <% if @student == current_user %>
        <div class="card-action">
          <%= link_to edit_student_path(@student), class: 'btn waves-effect waves-light' do %>
            <i class="material-icons right">create</i>Edit student profile
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>